%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Hridu\OneDrive\Documents\Stanford\SLAB 2017\Orbital Propagator\GravityCoefficients.xlsx
%    Worksheet: data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/09 13:19:25

%% Import the data
GravityCoefficients = xlsread('C:\Users\Hridu\OneDrive\Documents\Stanford\SLAB 2017\Orbital Propagator\GravityCoefficients.xlsx','data');

%% Clear temporary variables
clearvars raw;